---
- name: Check cluster was not yet initialized
  become: yes
  stat:
    path: /etc/kubernetes/admin.conf
  register: kubeadm_init

- name: kubeadm init
  become: yes
  shell: kubeadm init --apiserver-advertise-address="{{ master_ip }}" --apiserver-cert-extra-sans="{{ master_ip }}"  --node-name master --pod-network-cidr={{ pod_network_cidr }}
  when: kubeadm_init.stat.exists == False

- name: Configure kubectl
  become: yes
  shell: |
    mkdir -p $HOME/.kube
    cp -f /etc/kubernetes/admin.conf $HOME/.kube/config
    chown $(id -u):$(id -g) $HOME/.kube/config

- name: Install weave net
  become: yes
  shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')&env.IPALLOC_RANGE={{ pod_network_cidr }}"

- name: Copy kubectl config from guest to host
  become: yes
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: "/home/jcoimbra/projects/local_k8s/config.conf"
    flat: yes
